# Generated by Django 5.2 on 2025-04-22 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_instrumento_sala_aula'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AulaAgendada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('dia', models.IntegerField()),
                ('hora', models.TimeField()),
                ('data_agendamento', models.DateTimeField(auto_now_add=True)),
                ('alunos', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('instrumento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projeto.instrumento')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aulas_agendadas', to=settings.AUTH_USER_MODEL)),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projeto.sala')),
            ],
            options={
                'unique_together': {('sala', 'ano', 'mes', 'dia', 'hora')},
            },
        ),
    ]
