# Generated by Django 5.2 on 2025-05-11 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_agendamento_de_aula_aluno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento_de_aula',
            name='nome',
        ),
    ]
