# Generated by Django 5.2 on 2025-05-11 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_agendamento_de_aula_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deletaragendamento',
            name='nome',
        ),
        migrations.AddField(
            model_name='deletaragendamento',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.matricula'),
        ),
    ]
